version: '3.8'

services:
  # Bun API application (built from Dockerfile)
  app:
    build:
      context: . # Use Dockerfile in current directory
      target: development # Use development stage from Dockerfile
      dockerfile: Dockerfile # Explicitly specify Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp
      - AUTH_SECRET=your-secret-key
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # PostgreSQL database (using official image)
  db:
    image: postgres:15-alpine # Use official PostgreSQL image
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
